# Generated by Django 5.1.4 on 2025-09-02 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprador_nombre', models.CharField(max_length=150, verbose_name='Nombre del Comprador')),
                ('comprador_email', models.EmailField(max_length=254, verbose_name='Correo del Comprador')),
                ('comprador_tel', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos_vendidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
